#Patch can be wiped by samples operator
# Builder Image Build command - oc new-build https://github.com/MoOyeg/s2i-python-custom.git --name=s2i-ubi8-uvicorn --context-dir=s2i-ubi8-uvicorn -n openshift
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/display-name: Python
  name: python
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 3.8-python-uvicorn
      annotations:
        description: >-
          Build and run Python applications on UBI 8 with Gunicorn and uvicorn which can be used for ASGI Applications. For more information
          about using this builder image, including OpenShift considerations,
          see
          https://github.com/sclorg/s2i-python-container/blob/master/3.8/README.md.
        iconClass: icon-python
        openshift.io/display-name: Python 3.8 Uvicorn (UBI 8)
        openshift.io/provider-display-name: "Moyo"
        sampleRepo: "https://github.com/MoOyeg/testFlask"
        supports: "pypy,python:3.7,python,uvicorn,gunicorn"
        tags: "builder,python,pypy"
        version: "3.8"
      from:
        kind: DockerImage
        name: "image-registry.openshift-image-registry.svc:5000/openshift/s2i-ubi8-uvicorn:latest"
      referencePolicy:
        type: Local
